export interface Plant {
  id: string;
  common_name: string;
  botanical_name: string;
  type: 'tree' | 'large_shrub' | 'foundation_shrub' | 'perimeter_shrub' | 'filler';
  mature_width_ft: number;
  mature_height_ft: number;
  min_zone: number;
  max_zone: number;
  sun: 'full_sun' | 'part_shade' | 'full_shade' | 'adaptable';
  min_sun_hours: number;
  max_sun_hours: number;
  styles: Array<'modern_structured' | 'natural_wild' | 'desert_minimal' | 'traditional'>;
  priorities: Array<'low_maintenance' | 'curb_appeal' | 'pollinator' | 'kid_pet' | 'low_water' | 'privacy'>;
  is_anchor_capable: boolean;
  size_bucket: 'solo_specimen' | 'large' | 'medium' | 'small';
  spacing_ft: number;
}

// Source: plant_database_updated.numbers
// Styles: desert→desert_minimal, whimsical→natural_wild, modern→modern_structured, traditional→traditional
// Types: tree types→tree; shrubs≥60in tall→large_shrub; foundation use→foundation_shrub;
//        perimeter use (first)→perimeter_shrub; filler/groundcover/perennial/grass→filler
// Sun: full sun only→full_sun 6-14; part sun only→part_shade 3-6; full shade→full_shade 0-3; mixed→adaptable
// spacing_ft = width_in / 12 (mature width, center-to-center)

export const PLANTS: Plant[] = [

  // ── CACTI & SUCCULENTS ────────────────────────────────────────────────────

  {
    id: 'banana_yucca',
    common_name: 'Banana Yucca',
    botanical_name: 'Yucca baccata',
    type: 'foundation_shrub',
    mature_width_ft: 4, mature_height_ft: 4,
    min_zone: 5, max_zone: 9,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['desert_minimal'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water', 'curb_appeal'],
    is_anchor_capable: true,
    size_bucket: 'large',
    spacing_ft: 4,
  },
  {
    id: 'red_yucca',
    common_name: 'Red Yucca',
    botanical_name: 'Hesperaloe parviflora',
    type: 'foundation_shrub',
    mature_width_ft: 3, mature_height_ft: 4,
    min_zone: 5, max_zone: 10,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['desert_minimal'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water', 'curb_appeal'],
    is_anchor_capable: true,
    size_bucket: 'large',
    spacing_ft: 3,
  },
  {
    id: 'parrys_agave',
    common_name: "Parry's Agave",
    botanical_name: 'Agave parryi',
    type: 'filler',
    mature_width_ft: 3, mature_height_ft: 2,
    min_zone: 5, max_zone: 10,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['desert_minimal'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water'],
    is_anchor_capable: true,
    size_bucket: 'large',
    spacing_ft: 3,
  },
  {
    id: 'hens_and_chicks',
    common_name: 'Hens and Chicks',
    botanical_name: 'Sempervivum tectorum',
    type: 'filler',
    mature_width_ft: 1.5, mature_height_ft: 0.5,
    min_zone: 3, max_zone: 8,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['desert_minimal'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water'],
    is_anchor_capable: false,
    size_bucket: 'medium',
    spacing_ft: 1.5,
  },
  {
    id: 'plains_prickly_pear',
    common_name: 'Plains Prickly Pear',
    botanical_name: 'Opuntia polyacantha',
    type: 'filler',
    mature_width_ft: 1, mature_height_ft: 1,
    min_zone: 3, max_zone: 9,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['desert_minimal'],
    priorities: ['low_maintenance', 'low_water'],
    is_anchor_capable: true,
    size_bucket: 'medium',
    spacing_ft: 1,
  },
  {
    id: 'autumn_joy_stonecrop',
    common_name: 'Autumn Joy Stonecrop',
    botanical_name: "Sedum spectabile 'Autumn Joy'",
    type: 'filler',
    mature_width_ft: 2, mature_height_ft: 2,
    min_zone: 3, max_zone: 9,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['desert_minimal', 'traditional'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water', 'curb_appeal'],
    is_anchor_capable: true,
    size_bucket: 'medium',
    spacing_ft: 2,
  },
  {
    id: 'dragons_blood_stonecrop',
    common_name: "Dragon's Blood Stonecrop",
    botanical_name: "Sedum spurium 'Schorbuser Blut'",
    type: 'filler',
    mature_width_ft: 2, mature_height_ft: 0.5,
    min_zone: 3, max_zone: 9,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['desert_minimal', 'modern_structured'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water', 'curb_appeal'],
    is_anchor_capable: false,
    size_bucket: 'medium',
    spacing_ft: 2,
  },
  {
    id: 'claret_cup_cactus',
    common_name: 'Claret Cup Cactus',
    botanical_name: 'Echinocereus triglochidiatus',
    type: 'filler',
    mature_width_ft: 0.5, mature_height_ft: 1,
    min_zone: 5, max_zone: 9,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['desert_minimal'],
    priorities: ['low_maintenance', 'low_water', 'curb_appeal'],
    is_anchor_capable: true,
    size_bucket: 'small',
    spacing_ft: 1,
  },
  {
    id: 'purple_hardy_ice_plant',
    common_name: 'Purple Hardy Ice Plant',
    botanical_name: 'Delosperma cooperi',
    type: 'filler',
    mature_width_ft: 2, mature_height_ft: 0.2,
    min_zone: 5, max_zone: 9,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['desert_minimal', 'traditional'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water', 'curb_appeal'],
    is_anchor_capable: false,
    size_bucket: 'medium',
    spacing_ft: 2,
  },
  {
    id: 'jewel_of_the_desert_ice_plant',
    common_name: 'Jewel of the Desert Ice Plant',
    botanical_name: "Delosperma cooperi 'Jewel of the Desert Garnet'",
    type: 'filler',
    mature_width_ft: 1, mature_height_ft: 0.2,
    min_zone: 6, max_zone: 10,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['desert_minimal', 'traditional'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water', 'curb_appeal'],
    is_anchor_capable: false,
    size_bucket: 'small',
    spacing_ft: 1,
  },

  // ── SHRUBS ────────────────────────────────────────────────────────────────

  {
    id: 'beargrass',
    common_name: 'Beargrass',
    botanical_name: 'Nolina microcarpa',
    type: 'large_shrub',
    mature_width_ft: 6, mature_height_ft: 4,
    min_zone: 5, max_zone: 10,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['desert_minimal', 'traditional'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water'],
    is_anchor_capable: true,
    size_bucket: 'solo_specimen',
    spacing_ft: 6,
  },
  {
    id: 'mojave_sage',
    common_name: 'Mojave Sage',
    botanical_name: 'Salvia pachyphylla',
    type: 'filler',
    mature_width_ft: 3, mature_height_ft: 3,
    min_zone: 5, max_zone: 9,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['desert_minimal'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water', 'curb_appeal'],
    is_anchor_capable: true,
    size_bucket: 'large',
    spacing_ft: 3,
  },
  {
    id: 'winter_gem_boxwood',
    common_name: 'Winter Gem Boxwood',
    botanical_name: "Buxus sinica 'Winter Gem'",
    type: 'large_shrub',
    mature_width_ft: 6, mature_height_ft: 6,
    min_zone: 5, max_zone: 9,
    sun: 'adaptable', min_sun_hours: 3, max_sun_hours: 14,
    styles: ['traditional', 'modern_structured'],
    priorities: ['low_maintenance', 'kid_pet', 'privacy', 'curb_appeal'],
    is_anchor_capable: true,
    size_bucket: 'solo_specimen',
    spacing_ft: 6,
  },
  {
    id: 'bloomerang_purple_lilac',
    common_name: 'Bloomerang Purple Lilac',
    botanical_name: "Syringa 'Penda'",
    type: 'foundation_shrub',
    mature_width_ft: 5, mature_height_ft: 5,
    min_zone: 3, max_zone: 7,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['natural_wild', 'traditional'],
    priorities: ['low_maintenance', 'kid_pet', 'pollinator', 'low_water', 'curb_appeal'],
    is_anchor_capable: false,
    size_bucket: 'large',
    spacing_ft: 5,
  },
  {
    id: 'fernbush',
    common_name: 'Fernbush',
    botanical_name: 'Chamaebatiaria millefolium',
    type: 'foundation_shrub',
    mature_width_ft: 5, mature_height_ft: 5,
    min_zone: 4, max_zone: 10,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['natural_wild', 'traditional'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water', 'curb_appeal'],
    is_anchor_capable: false,
    size_bucket: 'large',
    spacing_ft: 5,
  },
  {
    id: 'dwarf_burning_bush',
    common_name: 'Dwarf Burning Bush',
    botanical_name: "Euonymus alatus 'Compactus'",
    type: 'large_shrub',
    mature_width_ft: 10, mature_height_ft: 20,
    min_zone: 4, max_zone: 9,
    sun: 'part_shade', min_sun_hours: 3, max_sun_hours: 6,
    styles: ['traditional', 'modern_structured'],
    priorities: ['low_maintenance', 'kid_pet', 'curb_appeal'],
    is_anchor_capable: false,
    size_bucket: 'solo_specimen',
    spacing_ft: 10,
  },
  {
    id: 'bluebeard',
    common_name: 'Bluebeard',
    botanical_name: 'Caryopteris clandonensis',
    type: 'foundation_shrub',
    mature_width_ft: 2, mature_height_ft: 3,
    min_zone: 5, max_zone: 9,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['modern_structured', 'natural_wild', 'desert_minimal', 'traditional'],
    priorities: ['low_maintenance', 'kid_pet', 'pollinator', 'low_water', 'curb_appeal'],
    is_anchor_capable: false,
    size_bucket: 'medium',
    spacing_ft: 2,
  },
  {
    id: 'variegated_red_twig_dogwood',
    common_name: 'Variegated Red Twig Dogwood',
    botanical_name: "Cornus alba 'Elegantissima'",
    type: 'large_shrub',
    mature_width_ft: 6, mature_height_ft: 8,
    min_zone: 2, max_zone: 8,
    sun: 'adaptable', min_sun_hours: 3, max_sun_hours: 14,
    styles: ['modern_structured', 'traditional'],
    priorities: ['low_maintenance', 'kid_pet', 'pollinator', 'curb_appeal'],
    is_anchor_capable: false,
    size_bucket: 'solo_specimen',
    spacing_ft: 6,
  },
  {
    id: 'seven_son_flower',
    common_name: 'Seven-Son Flower',
    botanical_name: 'Heptacodium miconioides',
    type: 'large_shrub',
    mature_width_ft: 10, mature_height_ft: 20,
    min_zone: 5, max_zone: 8,
    sun: 'adaptable', min_sun_hours: 3, max_sun_hours: 14,
    styles: ['natural_wild', 'traditional'],
    priorities: ['low_maintenance', 'kid_pet', 'pollinator', 'curb_appeal'],
    is_anchor_capable: false,
    size_bucket: 'solo_specimen',
    spacing_ft: 10,
  },
  {
    id: 'utah_serviceberry',
    common_name: 'Utah Serviceberry',
    botanical_name: 'Amelanchier utahensis',
    type: 'large_shrub',
    mature_width_ft: 10, mature_height_ft: 12,
    min_zone: 3, max_zone: 6,
    sun: 'adaptable', min_sun_hours: 3, max_sun_hours: 14,
    styles: ['natural_wild', 'traditional'],
    priorities: ['low_maintenance', 'pollinator', 'low_water'],
    is_anchor_capable: false,
    size_bucket: 'solo_specimen',
    spacing_ft: 10,
  },

  // ── PERENNIALS ────────────────────────────────────────────────────────────

  {
    id: 'english_lavender',
    common_name: 'English Lavender',
    botanical_name: 'Lavandula angustifolia',
    type: 'filler',
    mature_width_ft: 4, mature_height_ft: 3,
    min_zone: 4, max_zone: 9,
    sun: 'adaptable', min_sun_hours: 0, max_sun_hours: 14,
    styles: ['traditional', 'natural_wild', 'modern_structured'],
    priorities: ['low_maintenance', 'kid_pet', 'pollinator', 'curb_appeal'],
    is_anchor_capable: false,
    size_bucket: 'large',
    spacing_ft: 4,
  },
  {
    id: 'purple_coneflower',
    common_name: 'Purple Coneflower',
    botanical_name: 'Echinacea purpurea',
    type: 'filler',
    mature_width_ft: 1.5, mature_height_ft: 3,
    min_zone: 3, max_zone: 9,
    sun: 'adaptable', min_sun_hours: 3, max_sun_hours: 14,
    styles: ['traditional', 'natural_wild'],
    priorities: ['low_maintenance', 'kid_pet', 'pollinator', 'curb_appeal'],
    is_anchor_capable: false,
    size_bucket: 'medium',
    spacing_ft: 1.5,
  },
  {
    id: 'russian_sage',
    common_name: 'Russian Sage',
    botanical_name: 'Perovskia atriplicifolia',
    type: 'perimeter_shrub',
    mature_width_ft: 4, mature_height_ft: 4,
    min_zone: 5, max_zone: 9,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['traditional', 'natural_wild', 'desert_minimal'],
    priorities: ['low_maintenance', 'kid_pet', 'pollinator', 'low_water', 'curb_appeal'],
    is_anchor_capable: false,
    size_bucket: 'large',
    spacing_ft: 4,
  },
  {
    id: 'goblin_blanket_flower',
    common_name: 'Goblin Blanket Flower',
    botanical_name: "Gaillardia x grandiflora 'Kobold'",
    type: 'filler',
    mature_width_ft: 1.5, mature_height_ft: 1.5,
    min_zone: 3, max_zone: 9,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['traditional', 'natural_wild'],
    priorities: ['low_maintenance', 'kid_pet', 'pollinator', 'low_water', 'curb_appeal'],
    is_anchor_capable: false,
    size_bucket: 'medium',
    spacing_ft: 1.5,
  },
  {
    id: 'desert_penstemon',
    common_name: 'Desert Penstemon',
    botanical_name: 'Penstemon pseudospectabilis',
    type: 'filler',
    mature_width_ft: 1.5, mature_height_ft: 3,
    min_zone: 5, max_zone: 10,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['desert_minimal', 'natural_wild'],
    priorities: ['low_maintenance', 'kid_pet', 'pollinator', 'low_water', 'curb_appeal'],
    is_anchor_capable: false,
    size_bucket: 'medium',
    spacing_ft: 1.5,
  },
  {
    id: 'baja_daylily',
    common_name: 'Baja Daylily',
    botanical_name: "Hemerocallis 'Baja'",
    type: 'filler',
    mature_width_ft: 4, mature_height_ft: 2.5,
    min_zone: 3, max_zone: 9,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['traditional'],
    priorities: ['low_maintenance', 'kid_pet', 'pollinator', 'low_water', 'curb_appeal'],
    is_anchor_capable: false,
    size_bucket: 'large',
    spacing_ft: 4,
  },
  {
    id: 'coral_bells',
    common_name: 'Coral Bells',
    botanical_name: 'Heuchera sanguinea',
    type: 'filler',
    mature_width_ft: 1, mature_height_ft: 1,
    min_zone: 3, max_zone: 8,
    sun: 'adaptable', min_sun_hours: 0, max_sun_hours: 14,
    styles: ['traditional'],
    priorities: ['low_maintenance', 'kid_pet', 'pollinator', 'curb_appeal'],
    is_anchor_capable: false,
    size_bucket: 'medium',
    spacing_ft: 1,
  },
  {
    id: 'common_yarrow',
    common_name: 'Common Yarrow',
    botanical_name: 'Achillea millefolium',
    type: 'filler',
    mature_width_ft: 3, mature_height_ft: 3,
    min_zone: 3, max_zone: 9,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['desert_minimal', 'natural_wild', 'traditional'],
    priorities: ['low_maintenance', 'kid_pet', 'pollinator', 'low_water', 'curb_appeal'],
    is_anchor_capable: false,
    size_bucket: 'large',
    spacing_ft: 3,
  },
  {
    id: 'western_columbine',
    common_name: 'Western Columbine',
    botanical_name: 'Aquilegia formosa',
    type: 'filler',
    mature_width_ft: 1.5, mature_height_ft: 3,
    min_zone: 4, max_zone: 8,
    sun: 'adaptable', min_sun_hours: 0, max_sun_hours: 14,
    styles: ['natural_wild'],
    priorities: ['low_maintenance', 'kid_pet', 'pollinator', 'curb_appeal'],
    is_anchor_capable: false,
    size_bucket: 'medium',
    spacing_ft: 1.5,
  },
  {
    id: 'gooseberry_leaf_globemallow',
    common_name: 'Gooseberry-Leaf Globemallow',
    botanical_name: 'Sphaeralcea grossulariifolia',
    type: 'filler',
    mature_width_ft: 2, mature_height_ft: 3,
    min_zone: 3, max_zone: 8,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['natural_wild', 'desert_minimal'],
    priorities: ['low_maintenance', 'kid_pet', 'pollinator', 'low_water'],
    is_anchor_capable: false,
    size_bucket: 'medium',
    spacing_ft: 2,
  },
  {
    id: 'slender_cinquefoil',
    common_name: 'Slender Cinquefoil',
    botanical_name: 'Potentilla gracilis',
    type: 'filler',
    mature_width_ft: 2, mature_height_ft: 2,
    min_zone: 3, max_zone: 7,
    sun: 'adaptable', min_sun_hours: 3, max_sun_hours: 14,
    styles: ['natural_wild', 'desert_minimal'],
    priorities: ['low_maintenance', 'kid_pet', 'pollinator', 'low_water'],
    is_anchor_capable: false,
    size_bucket: 'medium',
    spacing_ft: 2,
  },
  {
    id: 'terracotta_yarrow',
    common_name: 'Terracotta Yarrow',
    botanical_name: "Achillea 'Terracotta'",
    type: 'filler',
    mature_width_ft: 3, mature_height_ft: 3,
    min_zone: 3, max_zone: 8,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['desert_minimal', 'natural_wild', 'traditional'],
    priorities: ['low_maintenance', 'kid_pet', 'pollinator', 'low_water'],
    is_anchor_capable: false,
    size_bucket: 'large',
    spacing_ft: 3,
  },
  {
    id: 'rocky_mountain_penstemon',
    common_name: 'Rocky Mountain Penstemon',
    botanical_name: 'Penstemon strictus',
    type: 'filler',
    mature_width_ft: 3, mature_height_ft: 2,
    min_zone: 3, max_zone: 8,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['desert_minimal', 'natural_wild', 'traditional'],
    priorities: ['low_maintenance', 'kid_pet', 'pollinator', 'low_water'],
    is_anchor_capable: false,
    size_bucket: 'large',
    spacing_ft: 3,
  },
  {
    id: 'sundial_lupine',
    common_name: 'Sundial Lupine',
    botanical_name: 'Lupinus perennis',
    type: 'filler',
    mature_width_ft: 2, mature_height_ft: 2,
    min_zone: 3, max_zone: 9,
    sun: 'adaptable', min_sun_hours: 3, max_sun_hours: 14,
    styles: ['natural_wild', 'traditional'],
    priorities: ['kid_pet', 'pollinator'],
    is_anchor_capable: false,
    size_bucket: 'medium',
    spacing_ft: 2,
  },
  {
    id: 'rocky_mountain_columbine',
    common_name: 'Rocky Mountain Columbine',
    botanical_name: 'Aquilegia caerulea',
    type: 'filler',
    mature_width_ft: 1.25, mature_height_ft: 1.5,
    min_zone: 3, max_zone: 10,
    sun: 'adaptable', min_sun_hours: 0, max_sun_hours: 14,
    styles: ['natural_wild', 'traditional'],
    priorities: ['low_maintenance', 'kid_pet', 'pollinator'],
    is_anchor_capable: false,
    size_bucket: 'medium',
    spacing_ft: 1.25,
  },
  {
    id: 'little_lanterns_columbine',
    common_name: 'Little Lanterns Columbine',
    botanical_name: "Aquilegia canadensis 'Little Lanterns'",
    type: 'filler',
    mature_width_ft: 0.83, mature_height_ft: 0.83,
    min_zone: 3, max_zone: 8,
    sun: 'adaptable', min_sun_hours: 0, max_sun_hours: 14,
    styles: ['natural_wild', 'traditional'],
    priorities: ['low_maintenance', 'kid_pet', 'pollinator'],
    is_anchor_capable: false,
    size_bucket: 'small',
    spacing_ft: 1,
  },
  {
    id: 'marin_pink_hummingbird_trumpet',
    common_name: 'Marin Pink Hummingbird Trumpet',
    botanical_name: "Epilobium canum 'Marin Pink'",
    type: 'filler',
    mature_width_ft: 4, mature_height_ft: 2,
    min_zone: 7, max_zone: 10,
    sun: 'adaptable', min_sun_hours: 3, max_sun_hours: 14,
    styles: ['natural_wild', 'desert_minimal'],
    priorities: ['low_maintenance', 'kid_pet', 'pollinator', 'low_water'],
    is_anchor_capable: false,
    size_bucket: 'large',
    spacing_ft: 4,
  },
  {
    id: 'desert_sunrise_hummingbird_mint',
    common_name: 'Desert Sunrise Hummingbird Mint',
    botanical_name: "Agastache 'Desert Sunrise'",
    type: 'filler',
    mature_width_ft: 3, mature_height_ft: 4,
    min_zone: 4, max_zone: 10,
    sun: 'adaptable', min_sun_hours: 3, max_sun_hours: 14,
    styles: ['natural_wild', 'desert_minimal', 'traditional'],
    priorities: ['low_maintenance', 'kid_pet', 'pollinator', 'low_water'],
    is_anchor_capable: false,
    size_bucket: 'large',
    spacing_ft: 3,
  },
  {
    id: 'texas_hummingbird_mint',
    common_name: 'Texas Hummingbird Mint',
    botanical_name: 'Agastache cana',
    type: 'filler',
    mature_width_ft: 1.5, mature_height_ft: 3,
    min_zone: 5, max_zone: 9,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['natural_wild', 'desert_minimal', 'traditional'],
    priorities: ['low_maintenance', 'kid_pet', 'pollinator', 'low_water'],
    is_anchor_capable: false,
    size_bucket: 'medium',
    spacing_ft: 1.5,
  },

  // ── ORNAMENTAL GRASSES ────────────────────────────────────────────────────

  {
    id: 'blue_oat_grass',
    common_name: 'Blue Oat Grass',
    botanical_name: 'Helictotrichon sempervirens',
    type: 'filler',
    mature_width_ft: 2, mature_height_ft: 2,
    min_zone: 4, max_zone: 9,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['modern_structured', 'desert_minimal'],
    priorities: ['low_maintenance', 'kid_pet', 'curb_appeal'],
    is_anchor_capable: true,
    size_bucket: 'medium',
    spacing_ft: 2,
  },
  {
    id: 'mexican_feather_grass',
    common_name: 'Mexican Feather Grass',
    botanical_name: 'Nassella tenuissima',
    type: 'filler',
    mature_width_ft: 2, mature_height_ft: 3,
    min_zone: 7, max_zone: 10,
    sun: 'adaptable', min_sun_hours: 3, max_sun_hours: 14,
    styles: ['natural_wild', 'desert_minimal'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water', 'curb_appeal'],
    is_anchor_capable: false,
    size_bucket: 'medium',
    spacing_ft: 2,
  },
  {
    id: 'karl_foerster_grass',
    common_name: 'Karl Foerster Feather Reed Grass',
    botanical_name: 'Calamagrostis x acutiflora',
    type: 'foundation_shrub',
    mature_width_ft: 2.5, mature_height_ft: 5,
    min_zone: 4, max_zone: 9,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['traditional', 'modern_structured'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water', 'curb_appeal'],
    is_anchor_capable: false,
    size_bucket: 'medium',
    spacing_ft: 2.5,
  },
  {
    id: 'indian_rice_grass',
    common_name: 'Indian Rice Grass',
    botanical_name: 'Achnatherum hymenoides',
    type: 'filler',
    mature_width_ft: 1.5, mature_height_ft: 2,
    min_zone: 3, max_zone: 9,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['natural_wild', 'desert_minimal', 'modern_structured'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water'],
    is_anchor_capable: true,
    size_bucket: 'medium',
    spacing_ft: 1.5,
  },

  // ── DECIDUOUS TREES ───────────────────────────────────────────────────────

  {
    id: 'city_sprite_zelkova',
    common_name: 'City Sprite Zelkova',
    botanical_name: "Zelkova serrata 'JFS-KW1'",
    type: 'tree',
    mature_width_ft: 18, mature_height_ft: 24,
    min_zone: 5, max_zone: 8,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['modern_structured', 'traditional'],
    priorities: ['low_maintenance', 'kid_pet'],
    is_anchor_capable: true,
    size_bucket: 'solo_specimen',
    spacing_ft: 18,
  },
  {
    id: 'fairmount_ginkgo',
    common_name: 'Fairmount Ginkgo',
    botanical_name: "Ginkgo biloba 'Fairmount'",
    type: 'tree',
    mature_width_ft: 12, mature_height_ft: 50,
    min_zone: 5, max_zone: 8,
    sun: 'adaptable', min_sun_hours: 3, max_sun_hours: 14,
    styles: ['traditional', 'natural_wild'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water'],
    is_anchor_capable: true,
    size_bucket: 'solo_specimen',
    spacing_ft: 12,
  },
  {
    id: 'princeton_sentry_ginkgo',
    common_name: 'Princeton Sentry Ginkgo',
    botanical_name: "Ginkgo biloba 'PNI 2720'",
    type: 'tree',
    mature_width_ft: 30, mature_height_ft: 50,
    min_zone: 3, max_zone: 8,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['traditional', 'natural_wild'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water'],
    is_anchor_capable: true,
    size_bucket: 'solo_specimen',
    spacing_ft: 30,
  },
  {
    id: 'imperial_honeylocust',
    common_name: 'Imperial Honeylocust',
    botanical_name: "Gleditsia triacanthos f. inermis 'Impcole'",
    type: 'tree',
    mature_width_ft: 35, mature_height_ft: 35,
    min_zone: 4, max_zone: 8,
    sun: 'adaptable', min_sun_hours: 3, max_sun_hours: 14,
    styles: ['traditional', 'natural_wild'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water'],
    is_anchor_capable: true,
    size_bucket: 'solo_specimen',
    spacing_ft: 35,
  },
  {
    id: 'shademaster_honeylocust',
    common_name: 'Shademaster Honeylocust',
    botanical_name: "Gleditsia triacanthos f. inermis 'Shademaster'",
    type: 'tree',
    mature_width_ft: 50, mature_height_ft: 70,
    min_zone: 5, max_zone: 8,
    sun: 'adaptable', min_sun_hours: 3, max_sun_hours: 14,
    styles: ['traditional', 'natural_wild'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water'],
    is_anchor_capable: true,
    size_bucket: 'solo_specimen',
    spacing_ft: 50,
  },
  {
    id: 'bur_oak',
    common_name: 'Bur Oak',
    botanical_name: 'Quercus macrocarpa',
    type: 'tree',
    mature_width_ft: 80, mature_height_ft: 90,
    min_zone: 3, max_zone: 8,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['traditional', 'natural_wild'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water'],
    is_anchor_capable: true,
    size_bucket: 'solo_specimen',
    spacing_ft: 80,
  },
  {
    id: 'rocky_mountain_maple',
    common_name: 'Rocky Mountain Maple',
    botanical_name: 'Acer glabrum',
    type: 'tree',
    mature_width_ft: 30, mature_height_ft: 30,
    min_zone: 5, max_zone: 9,
    sun: 'adaptable', min_sun_hours: 0, max_sun_hours: 14,
    styles: ['traditional', 'natural_wild'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water'],
    is_anchor_capable: true,
    size_bucket: 'solo_specimen',
    spacing_ft: 30,
  },
  {
    id: 'gambel_oak',
    common_name: 'Gambel Oak',
    botanical_name: 'Quercus gambelii',
    type: 'tree',
    mature_width_ft: 20, mature_height_ft: 25,
    min_zone: 4, max_zone: 8,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['traditional', 'natural_wild'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water'],
    is_anchor_capable: true,
    size_bucket: 'solo_specimen',
    spacing_ft: 20,
  },
  {
    id: 'jack_maze_oak',
    common_name: 'Jack Maze Oak',
    botanical_name: "Quercus 'Jack Maze'",
    type: 'tree',
    mature_width_ft: 18, mature_height_ft: 18,
    min_zone: 6, max_zone: 9,
    sun: 'adaptable', min_sun_hours: 3, max_sun_hours: 14,
    styles: ['natural_wild', 'traditional'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water'],
    is_anchor_capable: true,
    size_bucket: 'solo_specimen',
    spacing_ft: 18,
  },
  {
    id: 'eastern_redbud',
    common_name: 'Eastern Redbud',
    botanical_name: 'Cercis canadensis',
    type: 'tree',
    mature_width_ft: 30, mature_height_ft: 30,
    min_zone: 5, max_zone: 9,
    sun: 'adaptable', min_sun_hours: 0, max_sun_hours: 14,
    styles: ['natural_wild', 'traditional'],
    priorities: ['low_maintenance', 'kid_pet', 'curb_appeal'],
    is_anchor_capable: true,
    size_bucket: 'solo_specimen',
    spacing_ft: 30,
  },
  {
    id: 'autumn_brilliance_serviceberry',
    common_name: 'Autumn Brilliance Serviceberry',
    botanical_name: "Amelanchier x grandiflora 'Autumn Brilliance'",
    type: 'tree',
    mature_width_ft: 10, mature_height_ft: 25,
    min_zone: 4, max_zone: 9,
    sun: 'adaptable', min_sun_hours: 0, max_sun_hours: 14,
    styles: ['natural_wild', 'traditional'],
    priorities: ['low_maintenance', 'pollinator', 'low_water', 'curb_appeal'],
    is_anchor_capable: true,
    size_bucket: 'solo_specimen',
    spacing_ft: 10,
  },
  {
    id: 'common_hackberry',
    common_name: 'Common Hackberry',
    botanical_name: 'Celtis occidentalis',
    type: 'tree',
    mature_width_ft: 50, mature_height_ft: 60,
    min_zone: 4, max_zone: 9,
    sun: 'adaptable', min_sun_hours: 3, max_sun_hours: 14,
    styles: ['natural_wild', 'traditional'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water'],
    is_anchor_capable: true,
    size_bucket: 'solo_specimen',
    spacing_ft: 50,
  },
  {
    id: 'beijing_gold_tree_lilac',
    common_name: 'Beijing Gold Tree Lilac',
    botanical_name: "Syringa pekinensis 'Zhang Zhiming'",
    type: 'tree',
    mature_width_ft: 15, mature_height_ft: 20,
    min_zone: 3, max_zone: 7,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['traditional', 'modern_structured'],
    priorities: ['low_maintenance', 'kid_pet', 'curb_appeal'],
    is_anchor_capable: true,
    size_bucket: 'solo_specimen',
    spacing_ft: 15,
  },
  {
    id: 'desert_willow',
    common_name: 'Desert Willow',
    botanical_name: 'Chilopsis linearis',
    type: 'tree',
    mature_width_ft: 25, mature_height_ft: 25,
    min_zone: 7, max_zone: 10,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['desert_minimal', 'natural_wild'],
    priorities: ['low_maintenance', 'kid_pet', 'pollinator', 'low_water', 'curb_appeal'],
    is_anchor_capable: true,
    size_bucket: 'solo_specimen',
    spacing_ft: 25,
  },
  {
    id: 'mimosa',
    common_name: 'Mimosa',
    botanical_name: 'Albizia julibrissin',
    type: 'tree',
    mature_width_ft: 35, mature_height_ft: 25,
    min_zone: 6, max_zone: 9,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['natural_wild', 'traditional'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water', 'curb_appeal'],
    is_anchor_capable: true,
    size_bucket: 'solo_specimen',
    spacing_ft: 35,
  },
  {
    id: 'singleleaf_ash',
    common_name: 'Singleleaf Ash',
    botanical_name: 'Fraxinus anomala',
    type: 'tree',
    mature_width_ft: 12, mature_height_ft: 12,
    min_zone: 5, max_zone: 9,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['desert_minimal'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water'],
    is_anchor_capable: true,
    size_bucket: 'solo_specimen',
    spacing_ft: 12,
  },

  // ── EVERGREEN TREES ───────────────────────────────────────────────────────

  {
    id: 'austrian_pine',
    common_name: 'Austrian Pine',
    botanical_name: 'Pinus nigra',
    type: 'tree',
    mature_width_ft: 40, mature_height_ft: 80,
    min_zone: 5, max_zone: 8,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['desert_minimal', 'traditional'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water'],
    is_anchor_capable: true,
    size_bucket: 'solo_specimen',
    spacing_ft: 40,
  },
  {
    id: 'green_tower_austrian_pine',
    common_name: 'Green Tower Austrian Pine',
    botanical_name: "Pinus nigra 'Green Tower'",
    type: 'tree',
    mature_width_ft: 2, mature_height_ft: 8,
    min_zone: 4, max_zone: 8,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['modern_structured', 'desert_minimal'],
    priorities: ['low_maintenance', 'kid_pet', 'privacy', 'low_water'],
    is_anchor_capable: true,
    size_bucket: 'medium',
    spacing_ft: 2,
  },
  {
    id: 'hoops_blue_spruce',
    common_name: "Hoop's Blue Spruce",
    botanical_name: "Picea pungens 'Hoopsii'",
    type: 'tree',
    mature_width_ft: 20, mature_height_ft: 50,
    min_zone: 2, max_zone: 7,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['traditional'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water', 'curb_appeal'],
    is_anchor_capable: true,
    size_bucket: 'solo_specimen',
    spacing_ft: 20,
  },
  {
    id: 'skyrocket_juniper',
    common_name: 'Skyrocket Juniper',
    botanical_name: "Juniperus scopulorum 'Skyrocket'",
    type: 'tree',
    mature_width_ft: 5, mature_height_ft: 15,
    min_zone: 3, max_zone: 8,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['traditional', 'desert_minimal'],
    priorities: ['low_maintenance', 'kid_pet', 'privacy', 'low_water'],
    is_anchor_capable: true,
    size_bucket: 'large',
    spacing_ft: 5,
  },
  {
    id: 'rocky_mountain_juniper',
    common_name: 'Rocky Mountain Juniper',
    botanical_name: 'Juniperus scopulorum',
    type: 'tree',
    mature_width_ft: 15, mature_height_ft: 40,
    min_zone: 4, max_zone: 9,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['traditional', 'desert_minimal'],
    priorities: ['low_maintenance', 'kid_pet', 'privacy', 'low_water'],
    is_anchor_capable: true,
    size_bucket: 'solo_specimen',
    spacing_ft: 15,
  },
  {
    id: 'bristlecone_pine',
    common_name: 'Bristlecone Pine',
    botanical_name: 'Pinus aristata',
    type: 'tree',
    mature_width_ft: 40, mature_height_ft: 40,
    min_zone: 4, max_zone: 8,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['desert_minimal'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water'],
    is_anchor_capable: true,
    size_bucket: 'solo_specimen',
    spacing_ft: 40,
  },
  {
    id: 'white_fir',
    common_name: 'White Fir',
    botanical_name: 'Abies concolor',
    type: 'tree',
    mature_width_ft: 30, mature_height_ft: 50,
    min_zone: 3, max_zone: 7,
    sun: 'adaptable', min_sun_hours: 0, max_sun_hours: 14,
    styles: ['traditional'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water'],
    is_anchor_capable: true,
    size_bucket: 'solo_specimen',
    spacing_ft: 30,
  },
  {
    id: 'emerald_arrow_bosnian_pine',
    common_name: 'Emerald Arrow Bosnian Pine',
    botanical_name: "Pinus heldreichii 'Emerald Arrow'",
    type: 'tree',
    mature_width_ft: 7, mature_height_ft: 15,
    min_zone: 5, max_zone: 7,
    sun: 'full_sun', min_sun_hours: 6, max_sun_hours: 14,
    styles: ['traditional', 'desert_minimal'],
    priorities: ['low_maintenance', 'kid_pet', 'low_water'],
    is_anchor_capable: true,
    size_bucket: 'solo_specimen',
    spacing_ft: 7,
  },
];
